### ISSUE TITLE
post-link.sh fails for jupyterlab

### ISSUE THREAD

**Issue by Lucaszw** [conda/constructor#144] opened 2017-11-28 23:31 UTC
I am trying to build a conda constructor with the following construct.yaml file:
```yaml
name: Microdrop
version: 0.0.1

install_in_dependency_order: True

channels:
  - https://conda.anaconda.org/lucaszw
  - https://conda.anaconda.org/sci-bots
  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/dfroger

specs:
  - python 3.5*
  - anaconda-client
  - nodejs 8*
  - jupyter_core
  - jupyter_client
  - jupyterlab

ignore_duplicate_files: True

installer_type: sh [osx]

post_install: post_install

license_file: LICENSE

welcome_image: welcome.png

```

Unfortunately, the install fails on os x with the following error message:

```bash
installing: jupyterlab-0.29.2-py35_0 ...
Error: post-link failed for: jupyterlab-0.29.2-py35_0
```

Calling the post-link command directly yields:

```python
Traceback (most recent call last):
  File "bin/jupyter-serverextension", line 4, in <module>
    import notebook.serverextensions
  File "/Users/lucaszw/microdrop/lib/python3.5/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/Users/lucaszw/microdrop/lib/python3.5/site-packages/notebook/nbextensions.py", line 23, in <module>
    from jupyter_core.paths import (
ImportError: No module named 'jupyter_core'
```

**Comment by mbargull** [comment] 2017-11-29 00:56
`jupyter_core` is a `noarch:python` package, hence this is likely a duplicate of #86.

**Comment by mcg1969** [comment] 2020-09-26 23:37
Sorry for the form letter here—I'm doing some issue cleanup right now and closing out some stale issues. Constructor 3.x was a significant rewrite, and so many of the issues filed before its release would need to be re-tested / re-verified. If you have good reason to believe this still needs to be addressed in 3.x, please feel free to re-open or file a new issue with additional information on how to reproduce the issue on the latest versions of constructor.

NOTE: I do think the noarch support solves this.

**Closed by mcg1969** 2020-09-26 23:37 UTC
