### ISSUE TITLE
How to use local packages 

### ISSUE THREAD

**Issue by cfrelet** [conda/constructor#405] opened 2020-10-13 15:43 UTC
Hi,

How can we use the local package instead of redownload them?
Basically I have some proxy issue and when I run constructor command it tries to get the packages again from the repo even if I have them already in my Conda env. Anyway we can add as an argument in the command or specify in the yaml file to use local packages instead of trying to reach them again?

**Comment by mcg1969** [comment] 2020-10-20 14:10
Our most recently merged PR #406 purports to solve issues related to proxies. Is it possible for you see if this new build fixes things? A conda package for this is available in the `dev` subchannel: `conda install ctools/label/dev::constructor`

**Comment by mcg1969** [comment] 2020-11-14 22:47
I'm going to close this one now for two reasons:
- I do believe #406 resolves important proxy issues, and is now in 3.2.0
- Since constructor relies heavily on conda's behavior for determining when to download packages, it is not likely that we can change this behavior too much from within constructor.
That said, please let us know if the above fix helps you. If not, consider opening a new issue and providing a bit more detail about how we could reproduce your problem. Thanks!

**Closed by mcg1969** 2020-11-14 22:47 UTC
