### ISSUE TITLE
Package any file

### ISSUE THREAD

**Issue by raphaeljolivet** [conda/constructor#330] opened 2020-02-12 09:17 UTC
Is there a way to package any other file (like a Notebook for instance) ?

Ideally, I would like to ship a python Notebook with all its dependencies and have Jupyter to be opened on it automatically. Can this be achieved ?

Thanks for your help.

**Comment by cjmartian** [comment] 2020-06-16 17:43
Hey @raphaeljolivet, thanks for leaving us an issue.

I'd recommend reading a list of the allowed fields here: https://github.com/conda/constructor/blob/master/CONSTRUCT.md
Particularly this: https://github.com/conda/constructor/blob/master/CONSTRUCT.md#post_install

I haven't tried doing what your suggesting, but I'm sure it could be done.

**Comment by mcg1969** [comment] 2020-08-27 17:19
@raphaeljolivet I actually think your idea is really interesting—to be able to ship a "blob" that self-extracts, activates the conda environment, and runs a command, whether it is a Jupyter Notebook or some other application. But I think what you're suggesting is closer to what PyInstaller does: https://www.pyinstaller.org/

**Comment by mcg1969** [comment] 2020-09-27 18:39
This is enough of a duplicate of #211 that I'm going to close it—but I will quote the original issue there.

**Closed by mcg1969** 2020-09-27 18:39 UTC
Labels: question, source-community
