### ISSUE TITLE
virtual_specs glibc

### ISSUE THREAD

**Issue by drewgilliam** [conda/constructor#850] opened 2024-09-04 19:13 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

The GLIBC version check introduced in #809 doesn't seem to be appropriate for alpine images with GLIBC installed.

#809 introduced `virtual_specs` to fail quickly if installed dependencies are not appropriate. The GLIBC check for alpine systems is [here](https://github.com/conda/constructor/pull/809/files#diff-d5126ee7f99e6583ba9574579ff73994eaf0eebcfdc792a6deb00a0dc2158f6eR40-R41), given by
```
# musl ldd will report musl version; call ld.so directly
system_glibc_version=$($(find /lib/ /lib64/ -name 'ld-linux-*.so*' 2>/dev/null | head -1) --version | awk 'NR==1{ sub(/\.$/, ""); print $NF}')
```

This fails for an alpine image with GLIBC installed such as the following docker
```
FROM docker:20.10.16

RUN apk del libc6-compat; \
    apk --no-cache add ca-certificates curl findutils; \
    curl -fsSLo /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub; \
    curl -fsSLo /tmp/glibc.apk https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.28-r0/glibc-2.28-r0.apk; \
    apk add /tmp/glibc.apk;

RUN LD_SO=$(find /lib/ /lib64/ -name 'ld-linux-*.so*' 2>/dev/null | head -1); \
    ${LD_SO} --version
```

The final line of the docker, mimicking the GLIBC test of `virtual_specs`, fails with the following error
```
--version: error while loading shared libraries: --version: cannot open shared object file
```

Is there a more appropriate test for the GLIBC version in an alpine docker?

Thanks in advance for any help!

**Comment by jaimergp** [comment] 2024-09-05 07:20
Hm, that looks like we couldn't find the .so in those directories. I'll check your reproducer and report back.

**Comment by jaimergp** [comment] 2024-09-10 08:04
Turns out that this ld.so doesn't implement `--version` or `--help` or anything that would report the version of GLIBC. I haven't found a way to find this (easily or at all) in this particular Docker image. If you come up with more or less simple way of checking it (e.g. no compilation steps, just CLI calls), then we can look into a adding it to the existing checks.

**Comment by jaimergp** [comment] 2024-09-13 08:08
We merged https://github.com/conda/constructor/pull/856 now, so I think this can be closed. Want to give `main` a try @drewgilliam?

**Closed by jaimergp** 2024-09-13 08:08 UTC
Labels: type::bug
