### ISSUE TITLE
Problems with Qt5 and Numpy DLLs

### ISSUE THREAD

**Issue by bburan** [conda/constructor#223] opened 2018-10-04 20:48 UTC
I created an installer using conda constructor. However, when I tested it on Windows 7 (64 bit), it does not appear to be updating the system path properly. For example, when I try to run my application (e.g., `abr_gui.exe`), it fails and exits since it's unable to load Numpy and/or Qt5 DLLs. When I test via python.exe:

    import numpy

or

    from enaml import qt

Both fail due to DLL issues. However, when I manually append `%INSTALLDIR%\Library\bin` to the system path, everything works. Am I doing something wrong?

For details, I created the package using this `meta.yaml`:
```
{% set name = "abr" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: '../abr' 
   
build:

  entry_points:
    - abr_gui = abr.app.cmd_main:main
    - abr_loop = abr.app.cmd_main_loop:main

requirements:
  host:
    - python
    - setuptools
  run:
    - python >=3.6
    - matplotlib >=3.0.0
    - scipy
    - numpy
    - enaml
    - pandas
    - pytables

test:
  imports:
    - abr
    - abr.app
    - abr.data
    - abr.parsers
  commands:
    - abr_gui

about:
  home: https://github.com/bburan/abr
  license: BSD 3-clause
  license_family: BSD
  summary: GUI application for analyzing ABR waveforms

extra:
  recipe-maintainers:
    - bburan
```
and tried to create an installer using this `construct.yaml`:

    name: ABR-analysis
    version: 0.0.1

    channels:
        - file:///c:/users/bburan/Anaconda3/conda-bld
        - http://repo.anaconda.com/pkgs/main
        - http://repo.anaconda.com/pkgs/msys2

    specs:
        - abr

**Comment by mingwandroid** [comment] 2018-10-04 22:17
You probably failed to activate your conda environment.

**Comment by bburan** [comment] 2018-10-05 15:11
Thank you. I'm a bit confused about why this is necessary. For example, when I create an environment using `conda create --name envname`, I don't need to explicitly activate it. I can just create a Windows shortcut that points to `%anaconda_root%/envs/envname/Scripts/abr_gui.exe` and it works just fine. Although, perhaps it's just a coincidence that it even works in the first place (i.e., perhaps I don't realize that my program is pulling in the DLLs that are stored under the `base` environment)?

It seems that I need to add a post-install script to properly set up a launcher for my entry-point to activate the environment before running the program. Since `conda` is not included in the specs, how would I activate the environment? I could certainly include `conda` if necessary, but I was under the impression (from the docs) that conda was only required if one wished to use things like `conda install` from the Anaconda prompt for that particular install.

**Comment by mingwandroid** [comment] 2018-10-05 16:46
You are free to emulate the behaviour of conda activate (it does more than set path it calls the scripts too) in whatever language you wish as a wrapper script. Conda is a heavy dep (but a very useful one).

**Comment by bburan** [comment] 2018-10-05 16:52
Ok. Do you know why I don't need to activate when I use scripts installed in environments created using `conda create`? Is it just a coincidence that it works?

**Comment by mingwandroid** [comment] 2018-10-05 17:45
> Ok. Do you know why I don't need to activate when I use scripts installed in environments created using conda create? Is it just a coincidence that it works?

I do not understand this question. `conda activate` runs the activation scripts. It is programmed to do that. You have made a `constructor` installer without `conda`, so there's not way to run `conda` from that. You have two choices, bundle `conda` and tell your users how to `activate` properly (or add a menuinst shortcut to do that for them) or else emulate what `conda activate` does (modifies PATH and runs any activation scripts), probably with a batch file of your own creation.

Anyway, this is not a bug so I am closing it.

**Closed by mingwandroid** 2018-10-05 17:45 UTC

**Comment by bburan** [comment] 2018-10-05 19:39
@mingwandroid Ok, I see now. Thank you. Do you think this would be something worth mentioning in the docs?

**Comment by mingwandroid** [comment] 2018-10-05 22:42
A PR to add some docs somewhere may be helpful yes, providing an example batch file that people can integrate that performs activation for conda avoiders would be great too.

**Comment by mingwandroid** [comment] 2018-10-06 02:42
BTW, there's a similar project to `constructor` called `conda-pack`. It generates simple archives but has a way to run activation scripts I believe. It doesn't work on Windows at present but someone is working on that.

**Comment by bburan** [comment] 2018-10-09 15:55
Thanks! I didn't know about conda-pack. I'll research that as well.
