### ISSUE TITLE
Specify forcing single user install in construct.yaml?

### ISSUE THREAD

**Issue by scottwsides** [conda/constructor#298] opened 2019-10-10 21:43 UTC
Is there a way to force installing for a single user rather than choosing during the package extraction?

**Comment by msarahan** [comment] 2019-10-10 21:48
Not at present. We'd be happy to review a PR if you're interested in implemening this.

**Comment by scottwsides** [comment] 2019-10-10 22:04
I don't have time now. Maybe later. What would be involved in this?

**Comment by mcg1969** [comment] 2020-09-27 18:37
This is a duplicate of newly-created issue #396! Hopefully someone can take it up.

**Closed by mcg1969** 2020-09-27 18:37 UTC
