### ISSUE TITLE
Discussions about standalone app by python packaging people

### ISSUE THREAD

**Issue by matmel** [conda/constructor#243] opened 2019-02-22 17:26 UTC
Hi @msarahan, just to let you know, there is a discussion happening [here](https://discuss.python.org/t/standalone-app-deployment-story/920) that you may be interested in and could contribute to? As constructor is a way to achieve a standalone app, I think you experience could enlighten the discussion.

Thanks.

**Comment by msarahan** [comment] 2019-02-22 17:37
@matmel thanks for the pointer.  I'll see if I can add anything.  Constructor is not really a standalone app creator - more like a standalone installer creator of an environment, but perhaps it could be combined with other tools to make standalone apps.

**Comment by matmel** [comment] 2019-02-22 17:53
Right, thanks for the precision. I still think that constructor that has the ability to make installers for the 3 major platforms out of conda packages could be very well suited for the standalone app case.

**Comment by tjd2002** [comment] 2019-02-26 01:24
See also #211 for a suggestion of how conda-run (newly returned in conda 4.6) could enable this.

**Comment by mcg1969** [comment] 2020-09-27 14:59
Indeed, I will close this as a duplicate of #211

**Closed by mcg1969** 2020-09-27 14:59 UTC
