### ISSUE TITLE
Option to omit newly created install from environments.txt

### ISSUE THREAD

**Issue by hmaarrfk** [conda/constructor#373] opened 2020-08-30 16:09 UTC
I'm trying to use constructor to package up an application for deployment to users that don't really care about conda, or the API of my application.

Unfortunately, it seems that the line:
```
"$CONDA_EXEC" install --offline --file "$PREFIX/pkgs/env.txt" -yp "$PREFIX" || exit 1
```
will add an entry to the user's `.conda/environments.txt` file.

Is there an option we can use to omit this addition?

Can such a feature be added to `constructor`, or do we have to patch conda itself?

**Comment by hmaarrfk** [comment] 2020-08-30 17:35
If this helps anybody, I used the following in my post-install script

```bash
#!/usr/bin/env bash

# Remove the installed prefix name from the conda environments
# since we don't want this to be adapted by the user
# This strategy is likely not multi-processor safe, but we will assume
# That this is an unlikely scenerio.

# Don't use the forward slash as the delimiter
# so that we can remove the line that contains
sed -i "\,${PREFIX},d" ${HOME}/.conda/environments.txt || exit 0
```

**Comment by mingwandroid** [comment] 2020-08-30 17:36
I wish this file didn't exist but it's to late for that. A conda setting to not touch it (even reading it) would seem appropriate to me.

**Comment by mingwandroid** [comment] 2020-08-30 17:36
Yeah conda probably needs to handle this.

**Comment by hmaarrfk** [comment] 2020-08-30 17:38
Thanks for the quick feedback.

I have to say, that now that my immediate challenge has been solved, I am much less inclined to solve this myself, but hopefully this can help future users understand the limitations and others can use this issue as motivation to add a feature to conda.

**Comment by mcg1969** [comment] 2020-08-30 21:44
Actually, good news folks—conda does _not_ need to be patched to handle this. I have been working on a fix to #302 to prevent `constructor` to be influenced by someone's local `.condarc`. The only way I found to do this is to temporarily change the `HOME` or `USERPROFILE` value. A side effect of this work is that it ends up writing to a temporary `environments.txt`. Because I wanted to _preserve_ that behavior, I am jumping through hoops to ensure those changes propagate to `~/.conda/environments.txt`.

Stop jumping through those hoops, and boom—problem solved. Of course it would need to be an option to disable this.

**Comment by mcg1969** [comment] 2020-08-30 22:03
@hmaarrfk is your use case, judging by #372, to be able to distribute Python environments that don't include conda?

If so, then perhaps it's not something that needs an option. Suppose you're a user that doesn't care about conda and is only a consumer of your Python environments. Then no matter how may installers I use, `conda` is never in any of them. So what if the rule is this: _only add to `environments.txt` if conda is in the installer itself _or_ if the `.conda/` directory already exists.

**Comment by mcg1969** [comment] 2020-09-06 20:40
I've been thinking about this more. If conda is _not_ included in the environment, then this is still a conda environment that presumably needs to be formally activated. It's not enough, at least not always, to simply include the right directories from the environment in the PATH; there might be activation scripts to run. How are you handling that in your use case?

**Comment by hmaarrfk** [comment] 2020-09-06 21:23
hmm, very good point. Maybe i just have such a messed up default environment that things "seem" to be passing when they wouldn't be on an isolated test platform.

**Comment by mcg1969** [comment] 2020-09-06 21:29
Oh I'm sure constructor itself is working fine in your case. I'm just not sure what should be done with the environments it creates.

**Comment by hmaarrfk** [comment] 2020-09-06 22:41
The only entry point i want the user to know about in my case, is that of a GUI.

That said, the GUI will call a few applications (in the bin directory), so that is why i'm confused now.

Will have to try with a non-development machine.

**Comment by mcg1969** [comment] 2020-09-07 04:07
OK, so this really isn't the intended use case for constructor. Constructor is, after all, intended to basically make miniconda/Anaconda-style installers, which necessarily include conda in them.

That doesn't mean we can't make it happen. I just think it's important to make sure that we have the right behavior generically.

If you have a specific set of entrypoints you want to enable, then presumably what you want is for them to appear either in your global PATH (Unix) or on the Start Menu (Windows). When someone wants to call one of those entrypoints, it should fully activate the environment, and then run your application.

Interestingly, for Windows, this should work just fine, if you use a proper menuinst menu configuration for your application. For Windows, I'm not sure what should be done.

**Comment by mcg1969** [comment] 2020-09-27 15:17
I am going to close this but not because it shouldn't be pursued but because it is a duplicate of #211

**Closed by mcg1969** 2020-09-27 15:17 UTC
