### ISSUE TITLE
bogus "duplicate files" warning?

### ISSUE THREAD

**Issue by ywang007** [conda/constructor#163] opened 2018-01-19 02:04 UTC
It seems the constructor complains about same name **folders** in different packages, when check for duplicate files, please see the attached screenshot, it shows both the error, and the yaml file used.

<img width="753" alt="screen shot 2018-01-18 at 8 58 36 pm" src="https://user-images.githubusercontent.com/13110491/35131279-315de9f4-fc93-11e7-9367-faf1545671a4.png">

**Comment by nehaljwani** [comment] 2018-01-19 05:56
Which version of constructor are you using? This should have been fixed in 2.0.1 by https://github.com/conda/constructor/commit/b2d6d67452f5c6ace24886a2ba4b59b55885fe3a

**Comment by ywang007** [comment] 2018-01-19 15:08
I tried with both 2.0.1 and 2.0.0

When running 2.0.1 or 2.0.0 with latest conda (4.4.7), I got an “Can not import name fetch_repodata” error and can’t proceed.

When running 2.0.1 or 2.0.1 with conda 4.3.32, I got this “duplicate files” warning (which I can choose to ignore).

**Comment by nehaljwani** [comment] 2018-01-22 04:59
Okay, I can confirm that this problem occurs. However, this is not a bug in constructor, since `share/info/dir` is _actually_ a file and not a directory in those tarballs. Seems like we need to fix some packages. 
cc @mingwandroid @msarahan

**Comment by dasolyn** [comment] 2018-02-20 02:51
I have similar problem.

 - Console output of `constructor .`
```
platform: win-64
C:\Users\user\Miniconda3\envs\constructor\lib\site-packages\constructor\construct.py:253: UnsafeLoaderWarning:
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel_yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel_yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  return yaml.load(data)

Checking for duplicate files ...
Error: File 'Menu/jupyter.ico' found in multiple packages: notebook-5.0.0-py36_0.tar.bz2, qtconsole-4.3.1-py36_0.tar.bz2
```

 - constructor.yaml
```yaml
name: jupyter
version: 1.0.0

channels:
  - http://repo.continuum.io/pkgs/free

specs:
  - python
  - conda
  - pip
  - pandas
  - matplotlib
  - jupyter
  - notebook
  - scikit-learn
```

I am using Miniconda, Python 3.6.4, Constructor 2.0.2

**Comment by mingwandroid** [comment] 2018-02-20 09:52
You have 2 broken packages here. Why are you using the old `free` channel? You should use the new `main` channel instead.

**Comment by polwel** [comment] 2018-04-04 16:15
All the examples and even the main page are still referencing the `free` channel...

**Comment by mcg1969** [comment] 2020-09-26 23:48
Sorry for the form letter here—I'm doing some issue cleanup right now and closing out some stale issues. Constructor 3.x was a significant rewrite, and so many of the issues filed before its release would need to be re-tested / re-verified. If you have good reason to believe this still needs to be addressed in 3.x, please feel free to re-open or file a new issue with additional information on how to reproduce the issue on the latest versions of constructor.

**Closed by mcg1969** 2020-09-26 23:48 UTC
