### ISSUE TITLE
constructor self installer does not create .conda

### ISSUE THREAD

**Issue by briantoby** [conda/constructor#321] opened 2020-01-19 15:50 UTC
With constructor 3.0 installations on virgin Mac OS systems, I get this error message during the "Executing transaction" part of the installation: 

WARNING conda.core.envs_manager:register_env(46): Unable to register environment. Path not writable or missing. 
  environment location: /Users/toby/gsas2full
  registry file: /Users/toby/.conda/environments.txt

This warning goes away if I create the .conda directory before running the bash command (mkdir ~/.conda; bash...). I have not yet tried this in Linux (and of course Windows self-installs very differently).

**Comment by forrestwaters** [comment] 2020-01-20 13:53
Believe this should've been fixed by https://github.com/conda/constructor/pull/294 which is included in the constructor 3.0.1 tag if you'd like to try this off master. Looks like we may not have built packages for that release. We'll likely have another release in the next few weeks and will be sure those get updated.

**Comment by mcg1969** [comment] 2020-08-27 17:22
I have manually confirmed that this issue does not occur with the master build.

**Closed by mcg1969** 2020-08-27 17:22 UTC
