### ISSUE TITLE
constructor2.3 places noarch packages in <loc>\site-packages not <loc>\lib\site-packages

### ISSUE THREAD

**Issue by briantoby** [conda/constructor#253] opened 2019-04-20 17:01 UTC
With the construct.yaml file below on windows-10, the constructor 2.3-created installer places pytz and pyparsing in the wrong place: <install-loc>\site-packages rather than <install-loc>\lib\site-packages and they are not found for importing. These two packages are noarch (see https://anaconda.org/anaconda/pytz https://anaconda.org/anaconda/pyparsing), but if the previous version of each package is manually selected (each is platform-specific) the installer works fine.  Same problem with Constructor 2.2, so this is not recently introduced. 

```
name: gsas2full
version: 1.0.0
install_in_dependency_order: True

channels:
  - http://repo.continuum.io/pkgs/free/
  - http://repo.continuum.io/pkgs/main/

specs:
    - python=3.7
    - conda
    - numpy=1.15
    - scipy
    - matplotlib>=3.0.3
    - pillow
    - pyopengl
    - wxpython=4.0
    - svn
    - hdf5
    - h5py
    - imageio
    - pywin32                              [win]
    - python.app                           [osx]

exclude:
  - qt                               [not osx]
  - pyqt                             [not osx]
  - sip                              [not osx]
```

**Comment by newville** [comment] 2019-05-01 17:27
@briantoby I've run into the same problem, and not just on Windows.   It does seem sort of odd that noarch packages get installed, without warning, to a place they cannot be used.  Maybe I'm missing something, but I do not see how one could use constructor for a project that uses matplotlib. 
 
My workaround is to force a reinstall of these packages as part of the post-install process (for me, it is a couple more than pyparsing and pytz).   To be clear, I was already using post-install scripts a) to make desktop shortcuts for selected application entry points and b) to fix the entry point scripts to use `python.app` on MacOS.  So, adding another line wasn't a big deal.  The solution I use for this is at https://github.com/xraypy/xraylarch/tree/master/conda_constructor   It definitely seems like a hack to, but it works.  And, jut to be clear, I'm still sort of shocked at and very grateful for how easy `constructor` makes deployment of my apps.

**Comment by nehaljwani** [comment] 2019-06-27 22:34
Closing as duplicate of https://github.com/conda/constructor/issues/86

**Closed by nehaljwani** 2019-06-27 22:34 UTC
