### ISSUE TITLE
Excluding menuinst pacakge causes created installer to fail

### ISSUE THREAD

**Issue by Newtopian** [conda/constructor#338] opened 2020-05-05 01:49 UTC
Hi,

I've been toying around for a bit with creating my own conda installer so I can deploy a "secondary" conda installation for automation purposes without affecting any existing installation.

Most issues have been resolved but one : how to ensure start menu items are left untouched when installing / upgrading conda.  Once method that was recommended was to remove the menuinst package altogether hence my attempts with constructor with exclude of the menuinst package.

sadly when doing so it generates an installer that, will report a successful installation when in fact it left a half finished unusable mess.  Looking in the log window I could see the following :
```
ollecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

PackagesNotFoundError: The following packages are not available from current channels:

  - conda==4.8.3=py37_0 -> menuinst[version='>=1.4.11,<2']

Current channels:

  - http://repo.anaconda.com/pkgs/main/win-64
  - http://repo.anaconda.com/pkgs/main/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


Delete file: C:\ProgramData\ChekhovsConda\pkgs\env.txt
```
which is very similar to the error I got when I was using the normal miniconda installer but then manually remove the menuinst package from it...  it essentially becomes unusable until the package is restored.

so 1 - If the installation failed I would expect the constructor generated package to return a failure status and exit (ideally gracefully by un-doing the failed installation)

2 - How can I go about generating an installation of conda that could guarantee no global or user information is altered (start menu, registry, user path etc) ?

**Comment by mingwandroid** [comment] 2020-05-05 07:13
This is not a use-case that Anaconda needs to work so we will not have time to work on it. Constructor is open source though and contributions are welcome.

**Comment by mcg1969** [comment] 2020-09-27 18:38
This is actually a duplicate of #319

**Closed by mcg1969** 2020-09-27 18:38 UTC
