### ISSUE TITLE
constructor installer has missing packages

### ISSUE THREAD

**Issue by briantoby** [conda/constructor#323] opened 2020-01-31 23:46 UTC
I have created an installer using constructor 3.0 for OS X and tested it with 10.14 and 10.15 multiple times and it works fine for me. One user however had this error, also from installing in a  10.15: 

    Unpacking payload ...
    Collecting package metadata (current_repodata.json): done
    Solving environment: failed
    Collecting package metadata (repodata.json): done
    Solving environment: failed
    PackagesNotFoundError: The following packages are not available from current channels:
    - serf==1.3.9=hae1257d_0 -> openssl[version='>=1.1.1,<1.1.2.0a0']
    - cyrus-sasl==2.1.26=hb48c43a_4 -> openssl[version='>=1.1.1,<1.1.2.0a0']
    - gsas2complete==4261=0 -> svn=1.10 -> cyrus-sasl[version='>=2.1.26,<3.0a0'] -> openssl[version='>=1.1.1,<1.1.2.0a0']
    - gsas2complete==4261=0 -> svn=1.10 -> serf[version='>=1.3.9,<1.4.0a0']
    - svn==1.10.2=h670755d_0 -> cyrus-sasl[version='>=2.1.26,<3.0a0'] -> openssl[version='>=1.1.1,<1.1.2.0a0']
    - svn==1.10.2=h670755d_0 -> serf[version='>=1.3.9,<1.4.0a0']

I simply do not understand why this would be happening. Constructor is supposed to gather and include all needed packages. Also, why would extra packages be needed on some systems and not others? This sure seems like a bug in the installer.

**Comment by forrestwaters** [comment] 2020-02-01 00:04
I would have the user check the directory where the installer is being installed. Specifically, they should check to see if those packages exist and were extracted properly in the `pkgs` folder (that is where they need to exist for the install to succeed).

**Comment by mcg1969** [comment] 2020-08-29 19:04
I think this is caused by the fact that the installer's internal conda is picking up the local `.condarc`. In other words, I _think_ it is a duplicate of #302. Feel free to re-open if you disagree but I'm looking at that issue now.

**Closed by mcg1969** 2020-08-29 19:04 UTC
